### ISSUE TITLE
Attack on Titan 2 random crashes

### ISSUE THREAD

**Issue by konjiki7** [ZeroFox5866/nucleuscoop#10]
Event viewer is reporting the following error.

Faulting application name: AOT2_EU.exe, version: 2.0.5.0, time stamp: 0x5da7d555

Faulting module name: ntdll.dll, version: 10.0.18362.815, time stamp: 0xb29ecf52

Exception code: 0xc0000374

Fault offset: 0x00000000000f9229

Faulting process id: 0x1c4c

Faulting module path: \Windows\SYSTEM32\ntdll.dll

From my research c0000374 seems to be STATUS_HEAP_CORRUPTION or code related error. Seems to related to memory management.

**Comment by ZeroFox5866** [comment]
Hi for game specific support, please go to our discord: https://discord.gg/QDUt8HpCvr

And report your issue in one of the support channels.

Thanks.
