### ISSUE TITLE
Cannot find game\Cannot add game

### ISSUE THREAD

**Issue by vvvi333** [ZeroFox5866/nucleuscoop#14]
Great software, thank you for sharing.
But I encountered a problem, why can't I find the game? where is the problem?

Click "search" to select the game and prompt [Catastrophic failure].
Click "auto search" to find no game.
(╥﹏╥)

**Comment by ZeroFox5866** [comment]
Hi, you must download scripts first, using the "Download Scripts" button. Once you have the game scripts, then you can add the games. Immediately after downloading, you will get a prompt to add the game right then and there.
