### ISSUE TITLE
Star Wars Battlefront 2 will launch both instances but every time they freeze at the main screen

### ISSUE THREAD

**Issue by Zweezzy** [ZeroFox5866/nucleuscoop#16]
Im running the fresh install of Nucleus. 
fresh install of the steam edition of the game. doesn't work
also tried the SWBFSPY work around but that didn't work either.

it launches and runs perfect with no problems normally as well

any ideas?

**Comment by Zweezzy** [comment]
It stops responding here. no matter which way I try it. unless i open it normally through steam

![197c4f296e81756f48da6719fa708c2a](https://user-images.githubusercontent.com/76190765/102564979-67bff100-4091-11eb-80e7-7dd53a1c6a8b.jpg)

**Comment by Zweezzy** [comment]
Here is the debug log as well
[debug-log.txt](https://github.com/ZeroFox5866/nucleuscoop/files/5713233/debug-log.txt)

**Comment by Zweezzy** [comment]
Here is the debug log with "Game.HookInit = true;"
[debug-log-startup-hook.txt](https://github.com/ZeroFox5866/nucleuscoop/files/5713260/debug-log-startup-hook.txt)

[debug-log.txt](https://github.com/ZeroFox5866/nucleuscoop/files/5713259/debug-log.txt)

**Comment by Zweezzy** [comment]
Nucleus will launch both of them but them seem to get stuck trying to reposition them because both the applications are not responding. not sure where to go from here

**Comment by ZeroFox5866** [comment]
Hi for game specific support, please go to our discord: https://discord.gg/QDUt8HpCvr

And report your issue in one of the support channels.

Thanks.
