### ISSUE TITLE
1.0 R5 FINAL is not opening

### ISSUE THREAD

**Issue by neostun** [ZeroFox5866/nucleuscoop#18]
version 1.0 R5 FINAL is not opening (Windows defender disabled, opened as admin ), automatically crash without any gui showing, already have all the latest .net framework, and Visual C++ 2010-2017, also latest DirectX. the previous alpha mod 8 v0.9.9.9 r4 is working without issues. windows problem reporting opens in background and registers the error of 1.0 r5, already restarted and still isn't opening.

OS Windows 10 x64
Windows problem report event:
Origen
Nucleus Coop Tool (Mod)

Resumen
Dejó de funcionar

Fecha
‎26/‎12/‎2020 06:09 a. m.

Estado
Informe enviado

Descripción
Ruta de acceso de la aplicación con errores:	F:\GOG\NucleusCoop\NucleusCoop.exe

Firma del problema
Nombre de evento de problema:	CLR20r3
Firma del problema 01:	NucleusCoop.exe
Firma del problema 02:	2.0.0.8
Firma del problema 03:	5fe552b9
Firma del problema 04:	mscorlib
Firma del problema 05:	4.8.4300.0
Firma del problema 06:	5f7e60f6
Firma del problema 07:	339
Firma del problema 08:	10
Firma del problema 09:	System.ArgumentException
Versión de SO:	10.0.19041.2.0.0.256.48
Id. de configuración regional:	2058
Información adicional 1:	2beb
Información adicional 2:	2beba6fb4680d73a8c78ca7c24ccdb46
Información adicional 3:	f00e
Información adicional 4:	f00e6a5b10db5b51c8340a277c5e9536

Información adicional sobre el problema
Identificador de depósito:	22b70e87d3492c295943829a4e710998 (1820442273640417688)"

**Comment by zhinu** [comment]
Same issue here on windows 7. I tried to update and repair ms net framework but not working. The previous installment was functioning correctly!

**Comment by NIKO1714** [comment]
The same thing happens to me too, I tried everything to update the pc, deactivate the antivirus, restart the pc but nothing works since I try to open it but it does not allow the program to open, but the previous installment of the program (the previous update of the program ) if it worked.
Hopefully fix it since the program is very good and I recommend it but please fix this problem.

**Comment by ZeroFox5866** [comment]
Hi, can someone who is experiencing this issue please message me on Discord. I need some troubleshooting with someone.

My Discord is: ZeroFox#5866

Thanks.

**Comment by ZeroFox5866** [comment]
The issue for this been found. A hotfix will be released in the near future to fix this. Thanks.

**Comment by ZeroFox5866** [comment]
Update has been released that fixes this (v1.0.1).
