### ISSUE TITLE
1.0 R5 FINAL (The program) is not opening

### ISSUE THREAD

**Issue by NIKO1714** [ZeroFox5866/nucleuscoop#19]
The same thing happens to me too, I tried everything to update the pc, deactivate the antivirus, restart the pc but nothing works since I try to open it but it does not allow the program to open, but the previous installment of the program (the previous update of the program ) if it worked.
Hopefully fix it since the program is very good and I recommend it but please fix this problem.

**Comment by ZeroFox5866** [comment]
The issue for this been found. A hotfix will be released in the near future to fix this. Thanks.

**Comment by ZeroFox5866** [comment]
Update has been released that fixes this (v1.0.1).
