### ISSUE TITLE
[Bug] Nucleus Coop silently crashes when selecting any game

### ISSUE THREAD

**Issue by SirGouki** [ZeroFox5866/nucleuscoop#47]
I recently (in the last 15 minutes) downloaded the most recent release.  Before, I was running Mod8 v 0.9.9.9, and everything was working with the games I usually used it for (Borderlands 2, Borderlands the presequel, EDF4.1, and EDF5).  When I downloaded the most recent version (1.0.2 R5 Final), any time I selected one of my games, nucleus loads for a little bit, then closes itself.  At first, I thought it was because of Master Chief Collection, so I tried Earth Defence Force 5 the next time I ran it, since I know that one worked with 0.9.9.9, and it is also crashing.  Selecting any game in my list now crashes Nucleus, with no errors or anything, it's just gone.  I even tried deleting all my files in my nucleuscoop folder (except the scripts), and copying 1.0.2 back in from the zip, which does nothing.  Still crashes any time I pick any game.  I used Auto Search to replace my games list after deleting my files (and realized afterwords that I'd deleted my saves too).

I am not running any 3rd party antivirus, and windows defender says it hasn't found any threats, which it shouldn't be finding any because I have all the folders nucleus coop exists in (my downloads for the zip, and C:\Utilities\nucleuscoop) windows defenders' exceptions list.  I even double checked and its showing no threats have been detected or quarantined.

PC Stuff
Windows 10 home
Radeon RX 580
Ryzen 5 1600
24GB RAM (couldn't afford another 8 gb stick right now)

Other things I've noticed - Every version of nucleus coop I've run occasionally causes only my mouse to stutter for periods of time, especially when nucleus is starting a game (doesn't happen when I start games normally).  Also, nucleus sometimes makes my mouse completely disappear, leaving me to operate my computer by keyboard alone until the mouse comes back about 5 minutes later.  This happened as I was typing all this out.  Note, moving my games around is not an option - Master Chief Collection is 143GB, and I really don't want to wait around for 30 minutes - 2 hours for that to copy over.

Nucleus coop is on my C:\ and my games are on my E:\ and I never had any problems running the 4 games I previously mentioned, this all started when I tried to add Master Chief Collection and updated to the newest release.

Edit: forgot to mention I was trying to use 2 Xbox one controllers.  I removed one of them just now and tried again and its still crashing on selecting a game (one is wired, one is wireless plugged in to a usb charge cable as Windows' bluetooth has a habit of getting me killed in Dark Souls... more than I get myself killed normally).

**Comment by SirGouki** [comment]
As an extra step, I tried removing all the games from the list and readded EDF5 manually, and it still crashes when I select it.

**Comment by Ilyaki** [comment]
Could you check Event Viewer and see if there's any recent Error related to NucleusCoop?
Something like this perhaps
![image](https://user-images.githubusercontent.com/35632254/126871916-12182382-fb1f-498e-8988-7a4216826fa5.png)

**Comment by SirGouki** [comment]
Got three of those:
`Application: NucleusCoop.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentOutOfRangeException
   at System.String.Substring(Int32, Int32)
   at Nucleus.Gaming.Windows.User32Util+<>c__DisplayClass9_0.<GetDisplays>b__0(IntPtr, IntPtr, Nucleus.Interop.User32.Rect ByRef, Int32)
`
`
Application: NucleusCoop.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentOutOfRangeException
   at System.String.Substring(Int32, Int32)
   at Nucleus.Gaming.Windows.User32Util+<>c__DisplayClass9_0.<GetDisplays>b__0(IntPtr, IntPtr, Nucleus.Interop.User32.Rect ByRef, Int32)
`
`
Faulting application name: NucleusCoop.exe, version: 2.0.0.8, time stamp: 0x5ff0bc7c
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1110, time stamp: 0xc830c52d
Exception code: 0xc000041d
Fault offset: 0x0012b4b2
Faulting process id: 0x3fcc
Faulting application start time: 0x01d7807c819de680
Faulting application path: C:\Utilities\NucleusCoop\NucleusCoop.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 465c946d-bb0d-4629-b560-a599c2960d61
Faulting package full name: 
Faulting package-relative application ID: 
`

**Comment by Ilyaki** [comment]
Please try with the files here (copy them into your Nucleus folder) and let me know if it works. It appears to be a bug with processing the names of your display devices.
[Bugfix.zip](https://github.com/ZeroFox5866/nucleuscoop/files/6872920/Bugfix.zip)

**Comment by SirGouki** [comment]
That seems to work, I am at least getting passed selecting a game now.  It's also no longer slowing down or hiding my mouse.  I will edit this after I'm able to test running EDF5 on it again, I'm in the middle of something.

**Comment by Ilyaki** [comment]
Glad to hear it. Should be officially fixed in the next version.
