### ISSUE TITLE
Releases missing the executable

### ISSUE THREAD

**Issue by MoonStorm** [ZeroFox5866/nucleuscoop#6]
Thanks a lot for your hard work. I was wondering, since the releases only contain source code, is the expectation  for everyone to build the code or is there another website hosting the official releases? Thanks

**Comment by napserious** [comment]
@MoonStorm 
The last two versions (r2, r3) were taken down due some bugs. Please use v0.9.9.9 f1 until a new release.

**Comment by MoonStorm** [comment]
Thanks for the clarification. Stay safe and healthy.
