### ISSUE TITLE
7 days to die protoinput

### ISSUE THREAD

**Issue by GlyphAI** [ZeroFox5866/nucleuscoop#66]
every time I launch I get error protoinput failed to inject and only one window can be active the closest ive come to it working is right after hitting end to lock i hit Ctrl + T and it does a flickering cursor on both screens
![image](https://user-images.githubusercontent.com/6772418/144934700-c7d596ac-b8ed-49ad-8e5f-4d3f63fb53b6.png)

**Comment by Snailedlt** [comment]
What fixed the issue?
