### ISSUE TITLE
ERROR - Exception in Reset Window for instance 1 for Borderlands 3 + 1 other question

### ISSUE THREAD

**Issue by jmose64** [ZeroFox5866/nucleuscoop#7]
**ERROR - Exception in Reset Window for instance 1, error = System.NullReferenceException: Object refernce not set to an instance of an object.. at Nucleus.Gaming.GenericGameHandler.ResetWindows(ProcessData processData, Int32 x, Int32 y, Int32 w, Int32 h, Int32 i)**

I had this working fine the first boot and then it started doing this. I tried a fresh nucleuscoop and deleting the save/config files to no avail. Only thing I haven't tried is reinstalling the game.

I also had an issue where the game started stuttering very hard for no apparent reason after about 15 mins of 2 player gameplay. Both instances still get good FPS but the game stutters beyond playability.

Thanks.

**Comment by Snailedlt** [comment]
That's unfortunate, we'd like to help you, but there are not many helpers here on github, for some support please visit our discord: https://discord.gg/x38c88X
