### ISSUE TITLE
Archive is Either Unknown Format or Damaged

### ISSUE THREAD

**Issue by jasonr93** [ZeroFox5866/nucleuscoop#8]
Hello,
When I try to open up the latest release, Winrar is telling me that the file is either unknown format or damaged. Tried multiple times and on different drives. What program are you using to open up this .rar? As windows and winrar program that i typically use can't open it.

Thank you.

**Comment by napserious** [comment]
I'm also using Winrar for this. Uninstall WinRAR and install it again. Maybe it is broken.

**Comment by jasonr93** [comment]
Updating to the newest version of winrar allowed it to be extracted.
Thanks.
