### ISSUE TITLE
Download Last Release

### ISSUE THREAD

**Issue by dlazarosps** [ZeroFox5866/nucleuscoop#9]
Hi,
when downloading the latest release (NucleusCoop.Alpha.8.Mod.v0.9.9.9.r4.rar) and trying to extract the file it says the file is corrupted

I tried to download and extract a few times (winrar on windows 7 / Ubuntu 18.04 extract erro 04)

I tried too convert .rar into .zip with that I was able to extract the files, but the executable "stopped working" when click to run

some help?
- in addition to the download problem is there any prerequisite to run correctly on the machine?

- Besides that, how to compile from source code?

**Comment by jeremybris** [comment]
Try to extract with [7-zip](https://www.7-zip.org/)

**Comment by ZeroFox5866** [comment]
Not sure what is happening with the rar archive for you, but perhaps try downloading the file using different browsers or computer.

To answer your other questions -

Prerequisites:
.NET Framework 4.7.2 or higher
Microsoft Visual C++ 2015-2019 Redistributable (both x86 and x64)

To compile:
Download the source, open up the NucleusCoop solution file in your compiler, say Visual Studio 2019, and then build the solution.
